org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.200
neo_version_range=[21.1.200,21.2)
loader_version_range=[4,)

irons_spellbooks_version=1.21.1-3.16.2
irons_spellbooks_version_range=[1.21.1-3.16.2,1.21.1-4)
geckolib_version=4.7.5.1
player_animator_version=2.0.1+1.21.1
curios_version=9.5.1
irons_lib_version=1.21.1-2.1.0-SNAPSHOT

mod_id=temponottime
mod_name=Tempo Not Time
mod_version=1.2.3
mod_group_id=com.cappleapple.temponottime
mod_license=MIT
mod_authors=cappleapple
mod_description=Reinterprets Iron's mana economy as Casting Reserve, Casting Draw, charges, and recharge recovery.
